---
version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:202201-02
    working_directory: ~/rpmbuild-fedora-docker
    steps:
      - checkout
      - run: make build
      - deploy:
          name: push image to quay.io
          command: |
            if [[ "${CIRCLE_BRANCH}" == "master" ]]; then
              docker login -p "$QUAY_PASSWD" -u "$QUAY_USER" quay.io
              make push
            fi
